let data = [
    {
        id: 0,
        title : 'FRAGILE WORK CHORE',
        imgUrl_1 : '/img/detail/new0-1.jpg',
        imgUrl_2 : '/img/detail/new0-3.jpg',
        imgUrl_3 : '/img/detail/new0-4.jpg',
        imgUrl_4 : '/img/detail/new0-5.jpg',
        imgUrl_5 : '/img/detail/new0-2.jpg',
        color : 'MULTI',
        category : 'JACKET',
        price : 232000,
        code : 'DE24SSJAJL00263001',
        kor : '프래자일 워크 초어 멀티',
    },
    
    {
        id: 1,
        title : 'FANTASMA MOTO JERSEY',
        imgUrl_1 : '/img/detail/new10-1.jpg',
        imgUrl_2 : '/img/detail/new10-3.jpg',
        imgUrl_3 : '/img/detail/new10-2.jpg',
        imgUrl_4 : '/img/detail/new10-1.jpg',
        imgUrl_5 : '/img/detail/new10-2.jpg',
        color : 'BROWN COMBO',
        category : 'JERSEY',
        price : 95000,
        code : 'DE24SSTSLS02345001',
        kor : '판타스마 모토 져지 브라운 콤보'
    },
    {
        id: 2,
        title : 'OFR JACKET',
        imgUrl_1 : '/img/detail/new2-1.jpg',
        imgUrl_2 : '/img/detail/new2-3.jpg',
        imgUrl_3 : '/img/detail/new2-4.jpg',
        imgUrl_4 : '/img/detail/new2-5.jpg',
        imgUrl_5 : '/img/detail/new2-2.jpg',
        color : 'TOBACCO',
        category : 'JACKET',
        price : 325000,
        code : 'DE24SSJAJL00628001',
        kor : 'Ofr 자켓 타바코',
    },
    {
        id: 3,
        title : 'TICTAC LS TEE',
        imgUrl_1 : '/img/detail/new4-1.jpg',
        imgUrl_2 : '/img/detail/new4-3.jpg',
        imgUrl_3 : '/img/detail/new4-4.jpg',
        imgUrl_4 : '/img/detail/new4-5.jpg',
        imgUrl_5 : '/img/detail/new4-2.jpg',
        color : 'BLACK',
        category : 'T-shirt',
        price : 48000,
        code : 'DE24SSTSLS00002003',
        kor : '틱탁 긴팔 티 블랙',
    },
    {
        id: 4,
        title : 'FANTASMA MOTO JERSEY',
        imgUrl_1 : '/img/detail/new9-1.jpg',
        imgUrl_2 : '/img/detail/new9-3.jpg',
        imgUrl_3 : '/img/detail/new9-4.jpg',
        imgUrl_4 : '/img/detail/new9-5.jpg',
        imgUrl_5 : '/img/detail/new9-2.jpg',
        color : 'WHITE COMBO',
        category : 'JERSEY',
        price : 95000,
        code : 'DE24SSTSLS06572001',
        kor : '판타스마 모토 져지 화이트 콤보',
    },
    {
        id: 5,
        title : 'DEUS LOGO TEE',
        imgUrl_1 : '/img/detail/new5-1.jpg',
        imgUrl_2 : '/img/detail/new5-3.jpg',
        imgUrl_3 : '/img/detail/new5-4.jpg',
        imgUrl_4 : '/img/detail/new5-5.jpg',
        imgUrl_5 : '/img/detail/new5-2.jpg',
        color : 'FOREST GREEN',
        category : 'T-shirt',
        price : 48000,
        code : 'DE24SSTSSS00451002',
        kor : '데우스 로고 티 포레스트 그린',
    },
    {
        id: 6,
        title : 'AMPED COACH JACKET',
        imgUrl_1 : '/img/detail/new1-1.jpg',
        imgUrl_2 : '/img/detail/new1-3.jpg',
        imgUrl_3 : '/img/detail/new1-4.jpg',
        imgUrl_4 : '/img/detail/new1-5.jpg',
        imgUrl_5 : '/img/detail/new1-2.jpg',
        color : 'BLACK',
        category : 'JACKET',
        price : 185000,
        code : 'DE24SSJAJL00002005',
        kor : '앰페드 코치 자켓 블랙',
    },
   
    {
        id: 7,
        title : 'TRANSMISSION TEE',
        imgUrl_1 : '/img/detail/new7-1.jpg',
        imgUrl_2 : '/img/detail/new7-3.jpg',
        imgUrl_3 : '/img/detail/new7-4.jpg',
        imgUrl_4 : '/img/detail/new7-5.jpg',
        imgUrl_5 : '/img/detail/new7-2.jpg',
        color : 'ANTHRACITE',
        category : 'T-shirt',
        price : 48000,
        code : 'DE24SSTSSS05144008',
        kor : '트랜스미션 티 앤트러사이트',
    },
    {
        id: 8,
        title : 'STRIPES SHIRT',
        imgUrl_1 : '/img/detail/new3-1.jpg',
        imgUrl_2 : '/img/detail/new3-3.jpg',
        imgUrl_3 : '/img/detail/new3-4.jpg',
        imgUrl_4 : '/img/detail/new3-5.jpg',
        imgUrl_5 : '/img/detail/new3-2.jpg',
        color : 'MOOD INDIGO',
        category : 'JACKET',
        price : 135000,
        code : 'DE24SSSHLS00529001',
        kor : '스트라이프 셔츠 무드 인디고',
    },
    {
        id: 9,
        title : 'THREEPEAT MOTO JERSEY',
        imgUrl_1 : '/img/detail/new8-1.jpg',
        imgUrl_2 : '/img/detail/new8-3.jpg',
        imgUrl_3 : '/img/detail/new8-4.jpg',
        imgUrl_4 : '/img/detail/new8-5.jpg',
        imgUrl_5 : '/img/detail/new8-2.jpg',
        color : 'LEMON CHROME',
        category : 'JERSEY',
        price : 95000,
        code : 'DE24SSTSLS13294001',
        kor : '쓰리핏 모토 져지 레몬 크롬',
    },
    {
        id: 10,
        title : 'CURFEW HOODIE',
        imgUrl_1 : '/img/detail/new6-1.jpg',
        imgUrl_2 : '/img/detail/new6-3.jpg',
        imgUrl_3 : '/img/detail/new6-4.jpg',
        imgUrl_4 : '/img/detail/new6-5.jpg',
        imgUrl_5 : '/img/detail/new6-2.jpg',
        color : 'CAVIAR',
        category : 'T-shirt',
        price : 128000,
        code : 'DE24SSSWHO11430001',
        kor : '커퓨 후드 캐비어',
    },
    {
        id: 11,
        title : 'THREEPEAT MOTO JERSEY',
        imgUrl_1 : '/img/detail/new11-1.jpg',
        imgUrl_2 : '/img/detail/new11-3.jpg',
        imgUrl_3 : '/img/detail/new11-4.jpg',
        imgUrl_4 : '/img/detail/new11-5.jpg',
        imgUrl_5 : '/img/detail/new11-2.jpg',
        color : 'BLACK',
        category : 'JERSEY',
        price : 95000,
        code : 'DE24SSTSLS00002004',
        kor : '쓰리핏 모토 져지 블랙',
    }
]

export default data;